In [2]:
import pandas as pd
import numpy as np


df = pd.read_csv('dataset/synthetic_logs_train.csv')

df.head(3)

,timestamp,source,log_message,target_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert

In [3]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [4]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

### Clustering

In [5]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN


## Load pre-trained Sentence Transformer 
model = SentenceTransformer('all-MiniLM-L6-v2')

#Generate embeddings for the log messages
embeddings = model.encode(df['log_message'].tolist())
embeddings[:2]

/home/cyborg/.local/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1117.23it/s]

array([[-1.02939598e-01,  3.35459672e-02, -2.20261216e-02,
         1.55101111e-03, -9.86925978e-03, -1.78956240e-01,
        -6.34409934e-02, -6.01761788e-02,  2.81109102e-02,
         5.99620752e-02, -1.72618423e-02,  1.43358926e-03,
        -1.49560034e-01,  3.15287360e-03, -5.66031113e-02,
         2.71685515e-02, -1.49890641e-02, -3.54037993e-02,
        -3.62936519e-02, -1.45410383e-02, -5.61495451e-03,
         8.75539407e-02,  4.55120020e-02,  2.50964053e-02,
         1.00187557e-02,  1.24267498e-02, -1.39923573e-01,
         7.68696293e-02,  3.14095095e-02, -4.15246794e-03,
         4.36902344e-02,  1.71250012e-02, -8.00950974e-02,
         5.74006066e-02,  1.89092178e-02,  8.55262130e-02,
         3.96398790e-02, -1.34371787e-01, -1.44360214e-03,
         3.06703593e-03,  1.76854044e-01,  4.44889534e-03,
        -1.69274993e-02,  2.24266425e-02, -4.35049236e-02,
         6.09034114e-03, -9.98167321e-03, -6.23973198e-02,
         1.07372757e-02, -6.04894431e-03, -7.14660957e-02,
        -8.45803600e-03, -3.18019763e-02, -1.00518331e-01,
         2.25920172e-04, -1.89341232e-02, -3.17794010e-02,
         4.00861204e-02,  2.19178498e-02, -2.59529110e-02,
         5.84525391e-02, -8.12509432e-02,  2.12029219e-02,
        -5.02687693e-02,  1.32057425e-02,  1.32675422e-03,
         2.27062795e-02, -3.45793702e-02,  3.91546786e-02,
        -2.09433399e-02,  3.24826059e-03,  4.43961211e-02,
        -9.85357910e-02, -2.88894940e-02, -6.85025658e-03,
         5.38818836e-02,  6.46110475e-02, -2.45060697e-02,
         9.21828896e-02, -7.49868900e-02,  1.23994872e-02,
        -1.00026570e-01, -4.64910604e-02,  6.01570159e-02,
        -2.46480480e-02, -7.08075762e-02, -2.77270563e-02,
         9.72610861e-02,  3.85841355e-02, -1.44293299e-02,
        -7.46887701e-04, -1.04305437e-02, -1.61842890e-02,
         4.43627387e-02,  9.25998483e-03,  7.14165196e-02,
         6.37917072e-02,  4.94930707e-02, -6.02567494e-02,
         4.04805765e-02, -3.42860632e-02, -1.93881169e-02,
         6.61233813e-02,  6.01589642e-02,  1.09371087e-02,
        -5.38626825e-03,  1.44579932e-02,  9.25429687e-02,
        -3.14564183e-02, -1.84351448e-02,  9.91879404e-03,
        -1.85574330e-02,  1.31280627e-03,  2.26564571e-05,
         2.02741986e-03,  2.75257006e-02, -4.81928140e-02,
         5.42826205e-02, -7.32067227e-02,  4.88667525e-02,
         4.98489849e-02, -9.01149679e-03, -4.68906127e-02,
        -4.25886475e-02, -8.19524005e-02,  3.87106128e-02,
         7.85503909e-02,  1.46077052e-32,  1.66706536e-02,
         5.25493659e-02, -1.82449017e-02, -1.26686525e-02,
         6.52837902e-02, -2.11777259e-02, -4.06322815e-02,
         4.14947383e-02, -2.48360671e-02, -1.33068208e-02,
        -5.46753816e-02, -5.99147868e-04, -4.89245309e-03,
        -6.27359152e-02, -3.84878442e-02, -6.13543615e-02,
         8.27405602e-02,  2.34380029e-02, -8.63097981e-03,
         1.31002888e-02,  6.44215345e-02, -4.41361628e-02,
        -6.98633343e-02, -7.36060590e-02, -4.33263741e-02,
         6.96524745e-03, -5.05956598e-02, -1.60912238e-02,
        -5.66793978e-02,  3.35453940e-03,  5.34115024e-02,
         2.47761551e-02, -1.47986226e-02, -2.93243267e-02,
         7.30228275e-02, -1.86833888e-02,  8.13136920e-02,
        -2.69967001e-02, -5.68056367e-02, -6.59388751e-02,
        -5.95394103e-03,  2.85312943e-02, -7.85357878e-02,
        -2.76691420e-03, -3.26463743e-03, -9.28333253e-02,
        -7.27362931e-02, -3.31903510e-02,  1.01411112e-01,
         9.79882404e-02, -9.78740528e-02,  1.98667385e-02,
         2.38837134e-02, -1.81672703e-02, -3.73709127e-02,
         1.96547573e-03,  6.34426102e-02,  1.18271168e-02,
        -1.12041384e-02, -3.87316458e-02,  9.32424366e-02,
         4.26630490e-03, -1.66872535e-02, -6.87464252e-02,
         1.55120017e-02, -4.97755446e-02,  3.34492773e-02,
         8.00032392e-02,  2.12282483e-02,  1.34581879e-01,
        -2.30729990e-02,  5.53858504e-02,  3.07558607e-02,
        -2.93905474e-02,  2.31905431e-02, -9.34307724e-02,
         7.58034810e-02, -5.21205366e-03, -5.14523536e-02,
         3.32688875e-02,  3.67963240e-02, -1.06450496e-02,
         1.01635316e-02, -2.07651295e-02, -5.85518815e-02,
         4.79328372e-02,  2.13694666e-02,  8.76213312e-02,
         3.35492101e-03, -3.80336419e-02, -1.81204882e-02,
         6.87450916e-03,  5.15879653e-02, -4.75598760e-02,
        -6.12065792e-02, -1.45483560e-32,  4.12799558e-03,
         4.59643779e-03, -5.63900732e-02,  4.32462152e-03,
        -1.09439029e-03,  9.31957178e-03, -2.20269188e-02,
         5.79564609e-02, -1.44787645e-02,  4.64155450e-02,
         1.43542841e-01, -6.89756498e-02,  6.09631278e-02,
        -8.93743187e-02,  2.40919515e-02,  2.06010342e-02,
        -2.82415804e-02, -6.48315325e-02,  5.64795621e-02,
        -7.48339295e-03, -3.52057889e-02,  8.51060450e-02,
         1.30360024e-02,  2.02257484e-02, -1.44390836e-02,
        -4.63719033e-02,  1.77209694e-02,  1.59105882e-02,
        -9.51009244e-02, -3.54527086e-02,  2.08696052e-02,
         3.84389074e-03, -8.77918303e-02,  6.44575655e-02,
         1.44171165e-02,  3.84730217e-03,  4.70991656e-02,
         4.94661033e-02,  1.53862601e-02, -2.59578731e-02,
         9.10894424e-02,  1.83308143e-02, -5.89206107e-02,
         2.51992978e-02, -3.30374166e-02,  8.23344886e-02,
         1.74792279e-02,  6.48047403e-02, -1.19674457e-02,
        -3.31778489e-02,  3.00177652e-02,  3.54220010e-02,
        -1.39623899e-02,  6.69272915e-02,  3.87919992e-02,
         6.06916994e-02,  1.17958267e-03, -2.38786750e-02,
        -1.26930460e-01,  1.13846557e-02,  1.59290060e-02,
        -1.29426932e-02, -8.63247663e-02,  8.53659678e-03,
         6.03761412e-02,  1.51122091e-02, -1.19132318e-01,
         1.15234302e-02,  5.97089529e-02, -3.93345840e-02,
         1.55673195e-02,  1.04601849e-02, -4.72457111e-02,
        -2.59243418e-02,  9.98524390e-03,  3.07146292e-02,
        -7.14844689e-02,  6.98961644e-03, -1.55133093e-02,
         2.18864270e-02, -2.78145969e-02,  6.92733079e-02,
        -2.75903754e-02,  2.62429640e-02,  3.52561995e-02,
        -4.26419415e-02,  7.46307836e-04,  6.59866259e-02,
        -5.15105575e-02, -3.58433910e-02, -6.53439621e-03,
        -2.75858175e-02, -1.00125551e-01,  7.83325806e-02,
        -1.45799192e-02, -6.18457108e-08,  2.00325772e-02,
         6.59784824e-02, -2.04702914e-02,  1.64044313e-02,
         7.63001442e-02,  7.32182637e-02,  5.65789547e-03,
        -6.97766605e-04, -3.63798463e-03,  6.02393895e-02,
        -3.27187218e-02, -6.45838007e-02, -5.97952642e-02,
        -1.76696144e-02,  6.10144064e-03, -5.63489553e-03,
        -1.22972235e-01,  6.35818765e-02, -2.19431799e-02,
        -1.16406478e-01,  2.34366469e-02, -7.23525286e-02,
         2.31773555e-02, -6.55987188e-02, -7.42682219e-02,
         2.60145906e-02,  3.59758772e-02,  7.68432841e-02,
        -3.08057610e-02, -2.34794263e-02, -6.30425736e-02,
        -3.62157859e-02, -1.03559708e-02, -4.75602336e-02,
        -2.87522245e-02,  2.96400562e-02, -5.26893837e-03,
         5.67890070e-02, -3.74492886e-03,  3.09613030e-02,
         3.48227322e-02,  3.78607884e-02,  2.10155547e-02,
         2.70691570e-02,  5.25520481e-02,  7.16229454e-02,
        -5.53749548e-03,  4.01093923e-02,  5.16276583e-02,
        -2.67314818e-02,  5.94224036e-02, -4.29223962e-02,
        -1.19760521e-02,  3.05984858e-02, -7.40331933e-02,
         1.84222255e-02, -8.64862558e-03, -8.83557647e-02,
        -5.91984279e-02, -1.00867604e-04,  1.12913638e-01,
         4.57793847e-03, -4.25971970e-02,  3.22621269e-03],
       [ 8.04575067e-03, -3.57392207e-02,  4.93874103e-02,
        -7.19181867e-03,  6.17642945e-04, -9.05685350e-02,
         5.75595200e-02, -4.39446233e-02,  1.74751393e-02,
         5.21202944e-02, -4.62331921e-02,  2.49039140e-02,
         4.80811596e-02,  6.86636269e-02,  3.56146544e-02,
         3.00089270e-02,  2.61449497e-02, -9.05241370e-02,
        -8.02173913e-02,  5.04851267e-02, -7.90870711e-02,
        -1.76857784e-03, -2.48926990e-02,  9.02152807e-02,
         5.83696458e-03, -6.91071302e-02, -6.67965859e-02,
        -6.99111167e-03, -1.04566008e-01, -2.66474169e-02,
         3.05640139e-02,  2.02934444e-02,  2.25454494e-02,
        -4.22684010e-03,  1.11173131e-02,  6.78260773e-02,
         1.06073646e-02,  7.56636485e-02, -8.22777823e-02,
         8.45730025e-03, -6.97612315e-02, -4.21974473e-02,
        -1.05674686e-02,  2.23673228e-02,  5.64496629e-02,
         8.16503447e-03,  1.09344035e-01,  3.16565074e-02,
        -1.76924095e-02, -3.21071483e-02, -3.39975953e-02,
        -4.91812010e-04,  3.72878788e-03,  2.83771530e-02,
        -1.28521444e-02, -1.07930275e-03, -6.32419288e-02,
         6.89900964e-02,  1.77270453e-02, -5.20959720e-02,
         8.28305539e-03,  5.45032918e-02, -5.42099886e-02,
        -4.53332998e-02, -4.07494120e-02, -2.82698330e-02,
         1.23605849e-02, -2.13816185e-02, -2.36265939e-02,
         1.25318076e-02, -2.37170793e-02,  3.97411436e-02,
        -1.24362320e-01,  7.60625526e-02,  5.50833829e-02,
         8.28217119e-02,  2.97118742e-02, -1.84067339e-02,
        -1.96195189e-02,  5.54319471e-02, -3.49144749e-02,
        -4.14677933e-02, -3.37047502e-02,  7.31324106e-02,
         4.41836603e-02,  2.55246870e-02, -8.26404989e-03,
        -1.07323229e-02, -4.26243916e-02, -2.84965173e-03,
         7.38559216e-02,  2.27768198e-02,  7.15408649e-04,
         4.36012447e-02,  5.09079657e-02,  6.38482794e-02,
        -2.73155663e-02, -6.55021295e-02, -7.69265145e-02,
         3.55171748e-02,  9.60493833e-02,  2.18195748e-02,
         1.20154619e-02, -1.17863407e-02, -4.57925862e-03,
        -8.58036987e-03,  3.37150544e-02,  2.31917761e-02,
        -7.58325830e-02, -5.23879230e-02,  4.53934222e-02,
        -3.80785838e-02, -3.34905051e-02,  9.20352712e-02,
         2.87688486e-02, -3.33817117e-02, -1.95854995e-03,
        -3.04547313e-04, -1.70499161e-02,  2.85336003e-02,
        -8.81096721e-02, -4.02253196e-02, -4.00093198e-02,
        -1.03193112e-02, -2.51968335e-02,  2.14092992e-02,
         1.31045252e-01, -5.29632434e-34, -1.09651737e-01,
         1.29811289e-02,  5.92658063e-03,  4.73506190e-02,
        -8.60296190e-03, -3.67089286e-02,  3.05214990e-02,
         5.53066954e-02, -4.71985452e-02, -1.25119127e-02,
        -1.15366444e-01,  9.08000953e-03,  1.07346505e-01,
        -4.94734719e-02, -1.34290308e-02, -4.61562611e-02,
         2.45320629e-02,  9.45077930e-03,  2.04324033e-02,
        -3.99918631e-02, -4.67825867e-02,  2.21171305e-02,
        -4.58187014e-02, -8.13272502e-03, -7.65673630e-03,
         1.92284603e-02,  4.85845283e-02, -2.55903006e-02,
         1.61539461e-03, -1.37180407e-02,  9.67304688e-03,
         7.36416131e-03,  1.14088180e-02,  1.28853440e-01,
         7.71838846e-03,  7.06362352e-02,  2.54452005e-02,
         4.06523682e-02,  2.44039465e-02,  1.43777151e-02,
        -6.00932501e-02,  7.38180503e-02, -2.44700816e-02,
         8.98901597e-02,  3.17053031e-03,  1.01834498e-01,
         4.17742133e-02, -5.95177934e-02, -3.23181748e-02,
         3.80938575e-02,  1.21155707e-02, -4.07834426e-02,
         2.84823216e-02,  4.90988642e-02, -9.35704354e-03,
         6.50074035e-02,  7.23532364e-02, -1.67793538e-02,
        -8.22419394e-03, -1.61573030e-02,  5.96225224e-02,
        -3.36083509e-02,  2.12108362e-02, -6.06090687e-02,
         1.54377684e-01, -7.24146366e-02, -3.77272181e-02,
        -3.26890051e-02, -1.80386286e-03, -1.01960180e-02,
        -1.60676974e-03, -6.91847056e-02,  8.28444809e-02,
         9.88839641e-02,  3.45465308e-03, -9.90247875e-02,
        -3.52827050e-02, -7.13178664e-02, -4.96000312e-02,
        -3.43954638e-02, -8.13041925e-02,  4.81448174e-02,
         5.00681251e-03, -2.21499633e-02, -5.60056902e-02,
         1.00066736e-02, -3.59794162e-02,  1.06184304e-01,
        -4.54196893e-02,  7.16393664e-02, -2.36772951e-02,
         9.98142175e-03,  2.73602195e-02,  1.05985485e-01,
         4.60163839e-02,  9.59027525e-34, -1.12306930e-01,
         2.78912187e-02, -3.35900672e-02,  5.39242551e-02,
        -2.22291537e-02,  1.53769497e-02,  3.10411565e-02,
         3.39010879e-02,  7.43166879e-02,  3.42470780e-02,
        -3.35056777e-03, -2.05350816e-02, -3.62370275e-02,
         2.29334254e-02, -3.01991813e-02, -1.00819923e-01,
         3.29194404e-02,  6.77542537e-02,  1.35645121e-02,
        -5.20546595e-03, -6.58158958e-02,  9.54550654e-02,
        -1.34039139e-02,  1.53885940e-02, -7.22935945e-02,
         9.67835858e-02, -8.08119774e-02, -4.53450996e-03,
        -6.42011687e-02, -4.99278642e-02,  4.64197546e-02,
         2.21341439e-02,  3.13109308e-02,  9.13569257e-02,
        -4.61119972e-02, -1.02761172e-01,  3.04416064e-02,
         5.09876423e-02,  6.70141429e-02,  1.04043381e-02,
         1.63533818e-02,  3.92030925e-02,  2.17153896e-02,
         5.36603592e-02,  3.62809747e-02, -4.22140323e-02,
        -2.47227270e-02,  1.90311652e-02,  3.61723937e-02,
         6.37020916e-02, -3.21579026e-03, -8.50393157e-03,
         3.94655615e-02,  9.02655534e-03,  1.93096008e-02,
         6.60718083e-02,  1.02694705e-02, -4.43853736e-02,
        -1.56523027e-02, -1.55714527e-02,  1.32904528e-02,
        -1.16108749e-02,  4.21832204e-02, -5.44776395e-02,
         1.29237190e-01, -2.25756560e-02,  5.26203811e-02,
        -1.58436708e-02,  9.33164954e-02,  6.38026651e-03,
        -9.36161727e-03, -6.08876087e-02, -3.27308178e-02,
        -3.44816595e-02,  3.29973884e-02, -4.79391776e-02,
        -9.81300771e-02,  2.91165356e-02, -2.70903464e-02,
         1.81867108e-02, -1.73860267e-02, -4.40371558e-02,
        -7.97002539e-02,  3.01647615e-02, -6.35260940e-02,
         1.25963297e-02,  8.50250050e-02, -4.58910353e-02,
         5.81017211e-02, -2.71001812e-02,  8.42776075e-02,
        -4.09972407e-02, -3.37655917e-02,  1.02088330e-02,
        -2.54193228e-02, -1.40610306e-08,  4.94446568e-02,
        -9.04357135e-02, -6.06710128e-02,  8.29529390e-02,
        -3.29032615e-02,  4.14910465e-02,  9.99591406e-03,
         6.96134800e-03,  3.99232842e-03, -3.24332975e-02,
        -3.14657316e-02, -5.33161797e-02, -3.80913429e-02,
         1.62076931e-02,  2.45778598e-02, -7.26419464e-02,
        -6.56893626e-02, -8.23131725e-02, -8.00500736e-02,
        -5.36649153e-02,  5.60894869e-02, -1.10913198e-02,
         9.62172402e-04, -1.22690283e-01, -5.13836518e-02,
         9.96701699e-03,  1.00696394e-02,  1.07073061e-01,
         1.19758165e-02,  1.00423722e-02, -6.28261492e-02,
        -7.49697834e-02, -6.34075375e-03, -2.72201169e-02,
        -1.28096208e-01, -2.62459479e-02, -1.81464143e-02,
        -9.85360593e-02, -3.02990600e-02, -4.02614959e-02,
         9.94291008e-02,  5.35999574e-02,  2.74899472e-02,
        -5.53685613e-03,  8.43571052e-02,  8.35161880e-02,
         3.74304913e-02,  7.11937323e-02,  2.98902728e-02,
         2.32728366e-02, -3.62111889e-02,  6.20540082e-02,
         2.15148423e-02,  5.19732721e-02,  1.45337321e-02,
        -4.60966565e-02,  5.02554029e-02, -7.27027729e-02,
         2.92779356e-02,  5.62663004e-02, -3.86354961e-02,
         1.53831979e-02, -6.23095185e-02, -2.77465973e-02]], dtype=float32)

In [11]:
## Perform DBSCAN clustering
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

## ADD cluster labels to the DataFrame
df['cluster'] = clusters

In [12]:
df[df['cluster']==1].head(10)

,timestamp,source,log_message,target_label,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,1
477,12/2/2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,1
570,11/7/2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,1

In [14]:
cluster_counts = df['cluster'].value_counts()
print('number of clusters:', len(cluster_counts))

#   Get indices of large clusters
large_clusters = cluster_counts[cluster_counts > 10].index

for cluster in large_clusters:
    print(f"Cluster {cluster}:")
    print(df[df['cluster'] == cluster]['log_message'].head(5).to_string(index=False))
    print()

number of clusters: 136
Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...

Cluster 5:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-d38f479d-9bb9-4276-968...

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 85...
Multiple login failures occurred on user 9052 a...
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
Multiple login failures were detected for user ...

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
         Shard 6 replication task ended in failure
Data replication task for shard 14 did not comp...
         Data replication task failed for shard 17
            Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by use...
File data_3847.csv uploaded successfully by use...
File data_7366.csv uploaded successfully by use...
File data_1206.csv uploaded successfully by use...
File data_1503.csv uploaded successfully by use...

Cluster 17:
Denied access attempt on restricted account Acc...
Unauthorized login attempt on protected account...
   Account Account9437 blocked due to failed login
Account Account7999 access denied due to login ...
Invalid login attempt made on secured account A...

Cluster 6:
   Critical system unit error: unit ID Component55
System component malfunction: component ID Comp...
Critical system element is down: element ID Com...
Essential system part malfunction: part ID Comp...
Failure occurred in critical system component: ...

Cluster 32:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
   User 7662 tried to bypass API security measures
User 2367 failed to provide valid API access cr...
        User 3569 made an unauthorized API request
Unauthorized user 2968 tried to access restrict...
User 2186 attempted to access API without prope...

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...

Cluster 34:
Abnormal behavior found on server 10, possible ...
   Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, sec...
Server 27 experienced potential security incide...
Server 36 experienced potential security incide...

Cluster 53:
 Module X experienced an invalid data format issue
        Input format mismatch occurred in module X
Module X reported an error in input format vali...
Module X failed to process input due to formatt...
Input data format in module X was invalid or co...

Cluster 14:
   Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
      RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuratio...
Identification of multiple faulty disks in RAID...

Cluster 52:
Service health check was not successful because...
Invalid SSL certificate resulted in a failed se...
Service health check failure was due to an inva...
An issue with the SSL certificate caused the se...
Service health check failure was caused by an e...

Cluster 18:
Boot process terminated unexpectedly due to ker...
System encountered kernel panic during initiali...
    Boot process was stopped by kernel malfunction
System encountered kernel failure during bootup...
          Boot sequence failed due to kernel panic

Cluster 42:
User 5127 has escalated admin privileges withou...
            User 9745 has escalated to admin level
     User 8483 escalated privileges to admin level
            User 1987 has escalated to admin level
     User 8395 escalated privileges to admin level

Cluster 25:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 59:
Potential security threat: Admin privilege esca...
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege esca...
Warning: Potential admin privilege escalation f...

Cluster 26:
        Privilege elevation detected for user 5038
Elevation of admin privileges detected for user...
Elevation of admin privileges detected for user...
User 6069 has been granted elevated admin privi...
   Admin privilege elevation warning for user 7574

### Classification with Regex

In [15]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message):
            return label
    return None

In [16]:
## test
classify_with_regex("User User123 logged in.")

'User Action'

In [18]:
classify_with_regex("Backup started at 2023-08-01 10:00:00.")

'System Notification'

In [20]:
## no result because it is not in the pattern
classify_with_regex("hello")

In [ ]:
## applying regex classification
df['regex_label'] = df['log_message'].apply(lambda x: classify_with_regex(x))
df[df['regex_label'].notnull()].head(10)        # view classified logs

,timestamp,source,log_message,target_label,cluster,regex_label
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,4,System Notification
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,4,System Notification
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,8,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,9,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,11,User Action
30,4/26/2025 7:54,AnalyticsEngine,Backup started at 2025-05-14 07:06:55.,System Notification,13,System Notification
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,16,System Notification
44,6/20/2025 0:53,BillingSystem,Backup started at 2025-02-15 20:00:19.,System Notification,13,System Notification
48,7/1/2025 9:43,ModernHR,File data_7366.csv uploaded successfully by us...,System Notification,4,System Notification
50,1/16/2025 21:45,ThirdPartyAPI,System updated to version 3.9.1.,System Notification,21,System Notification

In [31]:
## total shape of the dataset
print('The shape of the dataset is:', df.shape[0])
print('Number of logs classified by regex:', df['regex_label'].notnull().sum())

### The remaining rows are not classified by regex
df_non_regex = df[df['regex_label'].isnull()].copy()
print('Number of logs NOT classified by regex:', df_non_regex.shape[0])

The shape of the dataset is: 2410
Number of logs classified by regex: 500
Number of logs NOT classified by regex: 1910

### Classification Stage 2: Classification using Embeddings

In [ ]:
df_non_regex.head(3)

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None

In [ ]:
## finding the target label that has the least cases in the dataset
print(df_non_regex['target_label'].value_counts(ascending=True))

target_label
Deprecation Warning       3
Workflow Error            4
Critical Error          161
Error                   177
Resource Usage          177
Security Alert          371
HTTP Status            1017
Name: count, dtype: int64

In [ ]:
## extractting target with values less than 5
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <= 5].index.tolist())

['Workflow Error', 'Deprecation Warning']

In [41]:
# finding the target label that has the small cases
df_non_regex[df_non_regex['target_label'].isin(['Workflow Error', 'Deprecation Warning'])].head()

,timestamp,source,log_message,target_label,cluster,regex_label
60,2025-10-06 16:55:23,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,24,None
255,2025-05-03 16:55:35,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,48,None
377,2025-06-24 12:16:29,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,62,None
1325,2025-04-17 07:33:44,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,105,None
1734,2025-04-30 07:47:30,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,118,None

In [43]:
df_non_legacy = df_non_regex[df_non_regex['source'] != 'LegacyCRM']
## find the unique vlaues
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [47]:
## generate embeddings for log messages

model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
embeddings_filtered = model.encode(df_non_legacy['log_message'].tolist())

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1584.35it/s]

In [48]:
len(embeddings_filtered)

1903

In [50]:
X = embeddings_filtered
y = df_non_legacy['target_label'].values

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [56]:
### Export the model 

import joblib

joblib.dump(clf, '../models/log_classifier.joblib')

['../models/log_classifier.joblib']